### ISSUE TITLE
error in running the code

### ISSUE THREAD

**Issue by helxsz** [guerrerocarlos/bitcoin-live-transactions#5]
```

var BLT = require("bitcoin-live-transactions")
var bitcoin = new BLT();
bitcoin.connect();

bitcoin.events.on('connected', function() {
   // start listening to addresses
});

bitcoin.events.on('138WJKb1mXbkRGNpyMVEZ9EsoXjMEvJfT4',function(tx){
  console.log('Transaction detected!', tx);
});
```
I am running the code above but got an error below, how can I solve it?
```
(node:75586) UnhandledPromiseRejectionWarning: Cannot reach any bitcoin insight server... no bitcoin transactions are being received.
(node:75586) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:75586) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

moreover 

TypeError: Cannot read property 'forEach' of undefined
    at /Users/xisizhe/Documents/projects/0xexchange/node_modules/bitcoin-live-transactions/index.js:46:48
    at Array.forEach (<anonymous>)
    at /Users/xisizhe/Documents/projects/0xexchange/node_modules/bitcoin-live-transactions/index.js:45:26
```

**Comment by itsLolo** [comment]
Yes, same here

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
dito
